# Formula for engx — local-first developer control plane.
# Auto-generated by engx-homebrew-update-20260321.sh
# Source: https://github.com/Harshmaury/Nexus
class Engx < Formula
  desc "Local-first developer control plane — run, monitor, and govern your services"
  homepage "https://github.com/Harshmaury/Nexus"
  version "1.7.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Harshmaury/Nexus/releases/download/v1.7.2/engx-1.7.2-darwin-amd64.tar.gz"
      sha256 "35714ddb9d4099f1946b572118ca26edb5d05d2c9cf0a02d74fc4e3b99631925"
    end

    on_arm do
      url "https://github.com/Harshmaury/Nexus/releases/download/v1.7.2/engx-1.7.2-darwin-arm64.tar.gz"
      sha256 "e8a6f4595df120ec20257f462a438aa7e74fc264b4f85acfb3f470137b0f5054"
    end
  end

  # Tarball layout (ADR-030): binaries land in bin/ at archive root.
  # wrap_in_directory: false — no top-level directory wrapper.

  def install
    bin.install "bin/engx"
    bin.install "bin/engxd"
    bin.install "bin/engxa"
  end

  def post_install
    # Create required directories for the daemon
    (var/"engx").mkpath
  end

  service do
    run [opt_bin/"engxd"]
    keep_alive true
    log_path var/"log/engxd.log"
    error_log_path var/"log/engxd.error.log"
    environment_variables HOME: Dir.home
  end

  def caveats
    <<~EOS
      engx has been installed with three binaries:
        engx   — CLI
        engxd  — platform daemon
        engxa  — remote agent

      Quick start:
        engx platform install   # register engxd as a system service
        engx init               # register your project
        engx run <project>      # start and confirm running
        engx doctor             # check platform health

      To start the daemon manually (without system service):
        engxd &

      Documentation: https://github.com/Harshmaury/Nexus
    EOS
  end

  test do
    # Verify all three binaries are installed and executable
    assert_match version.to_s, shell_output("#{bin}/engx --version")
    assert_predicate bin/"engxd", :executable?
    assert_predicate bin/"engxa", :executable?
  end
end
