# Formula for engx — local-first developer control plane.
# Auto-generated by engx-homebrew-update-20260321.sh
# Source: https://github.com/Harshmaury/Nexus
class Engx < Formula
  desc "Local-first developer control plane — run, monitor, and govern your services"
  homepage "https://github.com/Harshmaury/Nexus"
  version "1.7.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Harshmaury/Nexus/releases/download/v1.7.3/engx-1.7.3-darwin-amd64.tar.gz"
      sha256 "3cd653a49b92679bd4f9fecca1372cbf8798cb11d5e43eeb9db52640b2eb49e5"
    end

    on_arm do
      url "https://github.com/Harshmaury/Nexus/releases/download/v1.7.3/engx-1.7.3-darwin-arm64.tar.gz"
      sha256 "b93341601bc8b0257b2b5015b3c6d25d1f59651ed0fc8b62d08caa71ea6e2fa3"
    end
  end

  # Tarball layout (ADR-030): binaries land in bin/ at archive root.
  # wrap_in_directory: false — no top-level directory wrapper.

  def install
    bin.install "bin/engx"
    bin.install "bin/engxd"
    bin.install "bin/engxa"
  end

  def post_install
    # Create required directories for the daemon
    (var/"engx").mkpath
  end

  service do
    run [opt_bin/"engxd"]
    keep_alive true
    log_path var/"log/engxd.log"
    error_log_path var/"log/engxd.error.log"
    environment_variables HOME: Dir.home
  end

  def caveats
    <<~EOS
      engx has been installed with three binaries:
        engx   — CLI
        engxd  — platform daemon
        engxa  — remote agent

      Quick start:
        engx platform install   # register engxd as a system service
        engx init               # register your project
        engx run <project>      # start and confirm running
        engx doctor             # check platform health

      To start the daemon manually (without system service):
        engxd &

      Documentation: https://github.com/Harshmaury/Nexus
    EOS
  end

  test do
    # Verify all three binaries are installed and executable
    assert_match version.to_s, shell_output("#{bin}/engx --version")
    assert_predicate bin/"engxd", :executable?
    assert_predicate bin/"engxa", :executable?
  end
end
